name: Workstation Alert

on:
  push:
    tags:
      - 'alert-*' # Triggers only when a tag starting with "alert-" is pushed

jobs:
  fail_on_purpose:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Email Notification
        run: |
          echo "R Script completed!"
          exit 1